name = "DynamicPressures"
uuid = "3c4d1f6b-d2fc-45ad-886a-1f07bf4e7565"
authors = ["Paulo Jabardo <pjabardo@ipt.br>"]
version = "0.1.0"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
